service: events

# frameworkVersion: "=X.X.X"
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${file(config/serverless.${self:provider.stage}.yml):config.region}
  deploymentBucket:
      #name: com.events.serverless.${self:provider.region}.deploys
      memorySize: 256
      serverSideEncryption: AES256
  iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource:
          - Fn::Join:
            - ':'
            - - 'arn:aws:lambda'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - function:${self:service}-${self:provider.stage}-eventsList
  vpc:
    securityGroupIds: ${file(config/serverless.${self:provider.stage}.yml):config.securityGroupIds}
    subnetIds: ${file(config/serverless.${self:provider.stage}.yml):config.subnetIds}
  stackTags:
    TYPE: ServerLess
  stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Resource: "*"
      Condition:
        StringEquals:
          ResourceType:
            - AWS::EC2::Instance
  environment:
    DB_HOSTNAME: ${file(config/serverless.${self:provider.stage}.yml):config.database.hostname}
    DB_PORT: ${file(config/serverless.${self:provider.stage}.yml):config.database.port}
    DB_USERNAME: ${file(config/serverless.${self:provider.stage}.yml):config.database.username}
    DB_PASSWORD: ${file(config/serverless.${self:provider.stage}.yml):config.database.password}
    DB_DATABASE: ${file(config/serverless.${self:provider.stage}.yml):config.database.database}

custom:
  # Custom Domain (configured by stage)
  customDomain:
    domainName: ${file(config/serverless.${self:provider.stage}.yml):config.domain}
    basePath: 'demo'
    stage: ${self:provider.stage}
    createRoute53Record: true

  # Webpack Config
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

  # Config for serverless-offline
  serverless-offline:
      babelOptions:
        presets: ["env"]

# Endpoints
functions:
  # Function to check JWT validity
  authorize:
    handler: src/handlers/jwt.check
    environment:
      JWT_PUBLIC_KEY: ${file(config/serverless.${self:provider.stage}.yml):config.auth.jwt_public_key}

  eventsList:
    handler: src/handlers/events.list
    events:
      - http:
          path: /events
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  eventsRelist:
    handler: src/handlers/events.relist
    environment:
      LIST_ARN: ${self:service}-${self:provider.stage}-eventsList
    events:
      - http:
          path: /reevents
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  eventsShow:
    handler: src/handlers/events.show
    events:
      - http:
          path: /events/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              paths:
                id: true

  tasksList:
    handler: src/handlers/tasks.list
    events:
      - http:
          path: /tasks
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  tasksShow:
    handler: src/handlers/tasks.show
    events:
      - http:
          path: /tasks/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              paths:
                id: true

  tasksAirports:
    handler: src/handlers/airports.list
    memorySize: 128
    timeout: 2
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
            identitySource: method.request.header.authorization

          path: /airports
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false