config:
  subnetIds:
    - subnet-7xxxxxxx
    - subnet-9xxxxxxx
    - subnet-cxxxxxxx
  securityGroupIds:
    - sg-3xxxxxxx

  domain: dev-api-in.domain.com

  environment:
    VAR: Demo
    REGION: local
    ENDPOINT: http://localhost:8000
    ACCESSKEYID: "ACID"
    SECRETACCESSKEY: "SECRET"
    EVENTS_TABLE: NOTIF_TOKEN_SAVER_EVENTS

  dynamodb:
    notif_token_saver:
      table_suffix: "tokens"
      rcu: 5
      wcu: 5
